input_width: 256
input_height: 256
input_chanel: 3

batch_size: 32
epochs: 10

dataset: 'food101'
is_download: False

# tfrecor convert
train_row_images: 'datasets/fruits-360/train'
test_row_images: 'datasets/fruits-360/test'
image_extension: 'jpg'
saved_dir: 'datasets'
tfrecod_train_name: 'fruits_train.tfrecords'
tfrecod_test_name: 'fruits_test.tfrecords'
